sudo: required

services:
  - docker

install: true

jobs:
  include:
    - stage: latest
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - export IPFS_VERSION="v0.4.17"
        - export VERSION_TAG="ctheory/alpine-ipfs:$IPFS_VERSION"
        - docker build . -t $VERSION_TAG --build-arg IPFS_TAG=$IPFS_VERSION
        - docker push $VERSION_TAG
        - docker tag $VERSION_TAG ctheory/alpine-ipfs:latest
        - docker push ctheory/alpine-ipfs:latest
    - stage: versions
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - ./build_version_tags.sh
stages:
  - name: versions
    if: commit_message =~ /\[build versions\]/
  - latest
