sudo: required

services:
  - docker

install: true

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build --build-arg VCS_REF=`git rev-parse --short HEAD` . -t ctheory/alpine-ipfs:latest
  - docker push ctheory/alpine-ipfs:latest
